CC=gcc
CFLAGS=-headers

.PHONY: all clean

all: student_manager

student_manager: main.o
	$(CC) -o student_manager main.o $(CFLAGS)

main.o: main.c headers/studentStruct.h headers/studentInput.h headers/studentOperations.h headers/studentFilter.h headers/studentSort.h headers/studentPrint.h
	$(CC) -c main.c $(CFLAGS)

clean:
	rm -f *.o student_manager
